name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      run: |
        mkdir -p dist
        
        # Linux
        GOOS=linux GOARCH=amd64 go build -o dist/keyswap-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o dist/keyswap-linux-arm64 .
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -o dist/keyswap-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o dist/keyswap-darwin-arm64 .
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -o dist/keyswap-windows-amd64.exe .
        
        # Create checksums
        cd dist
        sha256sum * > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/keyswap-*
          dist/checksums.txt
        body: |
          ## Installation
          
          ### Linux/macOS
          ```bash
          # Download for your platform
          curl -L -o keyswap https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/keyswap-linux-amd64
          chmod +x keyswap
          sudo mv keyswap /usr/local/bin/
          ```
          
          ### Windows
          Download `keyswap-windows-amd64.exe` and add to your PATH.
          
          ### Verify integrity
          ```bash
          curl -L -o checksums.txt https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/checksums.txt
          sha256sum -c checksums.txt
          ```
          
          ## Usage
          ```bash
          keyswap user@hostname
          keyswap --port 2222 user@hostname
          ```
        draft: false
        prerelease: false